services:
  reverse-proxy:
    image: traefik:v3.3
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--providers.docker=true"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
        #- --log.filepath=/var/log/traefik.log
      - "--accesslog=true"

    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  blog-server:
    build:
      context: .
      dockerfile: Dockerfile.dev # explicitly specify Dockerfile for development
    develop:
      watch:
        - action: rebuild
          path: ./ui/templates
        - action: rebuild
          path: ./src
        - action: rebuild
          path: Cargo.toml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog-server.rule=Host(`localhost`)"
      - "traefik.http.routers.blog-server.entrypoints=web"
    volumes:
      - ./ui:/ui:ro
